### ISSUE TITLE
add checksum column in a sequencing file submission csv

### ISSUE THREAD

**Issue by sergpolly** [dekkerlab/cLIMS-docker#34]
@nandankita @betulakgol  would you think it is a good place to put md5sum/checksum of each raw fastq file in that csv submission form that we use to submit raw fastq files paths - like on  the picture here: https://github.com/dekkerlab/Various-Tools/issues/7

We have this field for checksums in the database but they are mostly empty now.

**Comment by nandankita** [comment]
As we talked I'll make the necessary changes in cLIMS side.
