### ISSUE TITLE
add sha256 alongside md5sum to the csv with fastq paths that we upload 

### ISSUE THREAD

**Issue by sergpolly** [dekkerlab/cLIMS-docker#42]
we've recently added `md5sum` column to the csv file with the fastq files locations that we upload to cLIMS: https://github.com/dekkerlab/cLIMS-docker/issues/34

cLIMS is actually aware of the both `md5sum` and `sha256` hash sums (there are such "columns" in the underlying database) ...

Thus there is no reason for us not to calculate `sha256` alongside the `md5sum` - 
1. we need to do some ground-work - i.e. enable cLIMS csv upload function to handle an extra `sha256` column
2. add `sha256` calculation in the https://github.com/dekkerlab/Various-Tools/blob/master/file_management/rename_arrange_pickup.sh scritp

**Comment by nandankita** [comment]
This is implemented on cLIMS side and deployed in production now. Please close this once above mentioned 2nd point is done.
