### ISSUE TITLE
Adding single end and/or paired end data to clims

### ISSUE THREAD

**Issue by betulakgol** [dekkerlab/cLIMS-docker#44]
Can we add single end fastq files to clims?
Does it still have to be 50x50 or we can add 100x100,..?

**Comment by nandankita** [comment]
We can add single end fastq files to cLIMS but this has to be done manually. Can not be imported with csv file. Have to add these under experiment > Files Wizard.

By default the import csv/ sequencing file populate the read length as 50. But if we manually add the files from  Files Wizard this can be populated to any desired length. If we still choose to import the files with csv then we have to go back and edit the files one by one to the correct read length.

**Comment by nandankita** [comment]
Closing this issue. Please reopen if anyone has more questions on this.
