### ISSUE TITLE
psycopg2 version is out of sync

### ISSUE THREAD

**Issue by sergpolly** [dekkerlab/cLIMS-docker#56]
clims containers fail to build with the `psycopg2==2.6.2` in the `config/pip-requirements.txt`
`2.7.2` seem to do it ...

**Comment by nandankita** [comment]
yeah I noticed while installing it with Snehal. Planning to fix it on Friday with Snehal's pull request.

**Comment by sergpolly** [comment]
huh, it took a while ... 2.7.4 worked, otherwise there were `glib` issues

**Comment by nandankita** [comment]
Fixed
