### ISSUE TITLE
Installing cLIMS locally-update

### ISSUE THREAD

**Issue by Snehal1894** [dekkerlab/cLIMS-docker#58]
@nandankita @sergpolly @betulakgol 
While installation of cLIMS, it installs all the packages which are in the file
'cLIMS-docker/Docker/config/pip-requirements.txt'
With the current version of cLIMS, which has 'psycopg2==2.6.2', the installation fails.
Use psycopg2==2.7.4 or 2.7.7.

**Comment by nandankita** [comment]
higher, I am not sure. Have you tested that?

**Comment by Snehal1894** [comment]
I am using 2.7.7  which is working.

**Comment by nandankita** [comment]
Yeah I only know 2.7.7 working. According to Sergey 2.7.4 is working. I know 2.8 is not working. Other than that it's not tested.

**Comment by nandankita** [comment]
We can merge these two issues, it's duplicate now. 
https://github.com/dekkerlab/cLIMS-docker/issues/56#issue-498443053

**Comment by Snehal1894** [comment]
Okay.
I specified the ones which are working. Updated the comment.

**Comment by nandankita** [comment]
Fixed
