### ISSUE TITLE
cLIMS setup on local machine- Postgres update

### ISSUE THREAD

**Issue by Snehal1894** [dekkerlab/cLIMS-docker#73]
While setting up cLIMS on my laptop, I can across an issue related to intializing the database.
This is because of the updates in Postgres 9.x images on Docker (it has to do with security).
It requires following lines to be added in **docker-compose.yml** file (either local or production depending on which we are running)
`environment:`
 `POSTGRES_DB: "db"`
 `POSTGRES_HOST_AUTH_METHOD: "trust"`

More info about this : http://support.divio.com/en/articles/3719228-database-is-uninitialized-and-superuser-password-is-not-specified

**Comment by nandankita** [comment]
Its new upgrade in Postgres image. Please go ahead with the above mentioned changes in docker-compose.yml files.

**Comment by sergpolly** [comment]
> There are updates in Postgres 9.x images available on Docker Hub, for security purposes. Now we either need to set password for specific user to get the connect or we can explicity mention that we allow all connection. We have done the later.
Git hub link for this change is : docker-library/postgres#658


resolved in #70
