### ISSUE TITLE
DCIC view excel sheet generation

### ISSUE THREAD

**Issue by Snehal1894** [dekkerlab/cLIMS-docker#74]
Error due to NoneType in `biosample_fields` attribute of Biosample model.
Jason object is returning NoneType.
Need to put a check on this.

**Comment by sergpolly** [comment]
> There are updates in Postgres 9.x images available on Docker Hub, for security purposes. Now we either need to set password for specific user to get the connect or we can explicity mention that we allow all connection. We have done the later.
Git hub link for this change is : docker-library/postgres#658

**Comment by sergpolly** [comment]
> Where there are no entries , it returns NoneType object.
In the database, some of the enzyme entries are empty.
So a check is added.

resolved in https://github.com/dekkerlab/cLIMS-docker/pull/70
