### ISSUE TITLE
Add automatic selection of experiments for DCIC page

### ISSUE THREAD

**Issue by Snehal1894** [dekkerlab/cLIMS-docker#75]
Right now, we need to manually select the experiments we need the DCIC file of.
This can be automated based on Experiment sets.

**Comment by sergpolly** [comment]
oh - that's a new feature looks like - right ?
and it is already in the https://github.com/dekkerlab/cLIMS-docker/pull/70 ?

**Comment by Snehal1894** [comment]
Yes it is added in #70

**Comment by Snehal1894** [comment]
"Correcting errors in DCICview exports"

**Comment by sergpolly** [comment]
> Yes, Initially in ExportDCIC, html page showed all experiments and if the selected exps were not in any Experiment set, it would not generate DCIC excel sheet
So we are now displaying Experiment Sets and the corresponding experiments on html page.
So the code is modified to handle experiments according to the Experiment Sets.

resolved in #70

**Comment by sergpolly** [comment]
also related:
> Intially the DCIC html page has just one table with all exps and all checkbox fields had name "dcic".
But now there are multiple tables on this page, consisting of exps for every expset.
In order to have (un)select all for each table of Exp Set, so the names are modified to include Exp Set id ( dcic(expset.id)" like dcic77)

> Also there is a button which should unselect al checkboxes, so I modified the code based on the "input type" to access all boxes on the page, and unselect them.

**Comment by sergpolly** [comment]
`dcicView.html` template related modifications:

> The HTML page is modified to display tables containing exps for each experiment set (expset).
Expset is a dictionary {Expset object: [all exp objects]}.
So for every Experiment Set (key in dictionary) a table is generated , with experiments in list (value of dictionary)

**Comment by sergpolly** [comment]
more changes:

> Yes. This is related to DCIC update. I needed the ExperimentSet Objects and also exps in it to send to html page.
so here dictionary is created sets.
It has `{Expset object: [all exp objects]}`
