### ISSUE TITLE
DCIC export related issue

### ISSUE THREAD

**Issue by sergpolly** [dekkerlab/cLIMS-docker#77]
I think this was split into #75 #74 - but prehaps it is nice to keep a more detailed version here as well

original email from @betulakgol - should have been a github issue - but it's ok

email 1 @betulakgol :
> I have problem exporting DCIC view for my project. So there are lots of experiments involved in the project but I want to export 63 of them. First, I needed to create an experiment set so I created analysis set with 63 experiments and then  tried to export the  DCIC View. But it gave me the error below. When I tried 12  experiments (of the same cell type)  or 27 experiments  (of the same cell type) at a time it worked.  I don’t know what this error related to. Let me know what you think and how can we solve this. Thank you!

![download (1)](https://user-images.githubusercontent.com/6790270/84434170-84203400-abfd-11ea-8812-e407da4ce5c4.png)

email 2 @Snehal1894 :
> This is because some column is not having entry.
I fixed few of these "NoneType" issues before.
Can you tell me your project and some experiment names.
I can check them on main cLIMS and try to do this myself and see the error then?

email 3 @betulakgol :
> entire U54

email 4 @Snehal1894 :
> I tried these experiments in groups (12,12,12 and 27) and together (63) as well.
It generated the DCIC files.
I have attached the DCIC excel sheet with 63 together.
> But when I tried all experiments together, it is generating the error.
So I will see this (by trying to look at experiments not in the list of 63, I think it is because of one of those)🤔
> Let me know if you still get an error with these 63 experiments.
(Also I hope I did what you were referring to)

skip a couple ...

> I did the same actually (selected manually). What I meant is if you try to get DCIC view for some other random experiments first,  it gives an error saying that these experiments need to be in experiment set. So I created an experiment set for these 63 experiments maybe that’s why it did not give you the same error. But later again you have to select these experiments manually 😔 I think it would be good to add an option of selecting all the experiments in specified experiment set. So you don’t need to select them manually. In this condition I don’t know what is the purpose of creating an experiment set. Maybe it is useful for replicates?

final one:
> There should be an option that just automatically selects the exps based on sets
It was a task to select them manually 😕 I will work on that.
Also, this error looks like because of biosample_fields (JASON object).
I will debug this and work on it.

**Comment by Snehal1894** [comment]
This is addressed in #70 .

**Comment by Snehal1894** [comment]
The "NoneType" issue is also resolved in #70 
Added the if condition to check if the object is "NoneType"

**Comment by sergpolly** [comment]
this is here just for the records, closing ..
